/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as TablesIndexRouteImport } from './routes/tables/index'
import { Route as TablesTableIdRouteImport } from './routes/tables/$tableId'
import { Route as ApiDebugStreamsRouteImport } from './routes/api/debug.streams'
import { Route as ApiSessionsSessionIdEventsRouteImport } from './routes/api/sessions.$sessionId.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesIndexRoute = TablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdRoute = TablesTableIdRouteImport.update({
  id: '/tables/$tableId',
  path: '/tables/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugStreamsRoute = ApiDebugStreamsRouteImport.update({
  id: '/api/debug/streams',
  path: '/api/debug/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdEventsRoute =
  ApiSessionsSessionIdEventsRouteImport.update({
    id: '/api/sessions/$sessionId/events',
    path: '/api/sessions/$sessionId/events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables/': typeof TablesIndexRoute
  '/api/debug/streams': typeof ApiDebugStreamsRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables': typeof TablesIndexRoute
  '/api/debug/streams': typeof ApiDebugStreamsRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables/': typeof TablesIndexRoute
  '/api/debug/streams': typeof ApiDebugStreamsRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/health'
    | '/sessions/$sessionId'
    | '/tables/$tableId'
    | '/tables/'
    | '/api/debug/streams'
    | '/api/sessions/$sessionId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/sessions/$sessionId'
    | '/tables/$tableId'
    | '/tables'
    | '/api/debug/streams'
    | '/api/sessions/$sessionId/events'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/sessions/$sessionId'
    | '/tables/$tableId'
    | '/tables/'
    | '/api/debug/streams'
    | '/api/sessions/$sessionId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TablesTableIdRoute: typeof TablesTableIdRoute
  TablesIndexRoute: typeof TablesIndexRoute
  ApiDebugStreamsRoute: typeof ApiDebugStreamsRoute
  ApiSessionsSessionIdEventsRoute: typeof ApiSessionsSessionIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/': {
      id: '/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof TablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId': {
      id: '/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof TablesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/streams': {
      id: '/api/debug/streams'
      path: '/api/debug/streams'
      fullPath: '/api/debug/streams'
      preLoaderRoute: typeof ApiDebugStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/events': {
      id: '/api/sessions/$sessionId/events'
      path: '/api/sessions/$sessionId/events'
      fullPath: '/api/sessions/$sessionId/events'
      preLoaderRoute: typeof ApiSessionsSessionIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TablesTableIdRoute: TablesTableIdRoute,
  TablesIndexRoute: TablesIndexRoute,
  ApiDebugStreamsRoute: ApiDebugStreamsRoute,
  ApiSessionsSessionIdEventsRoute: ApiSessionsSessionIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
