/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as TablesIndexRouteImport } from './routes/tables/index'
import { Route as TablesTableIdRouteImport } from './routes/tables/$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesIndexRoute = TablesIndexRouteImport.update({
  id: '/tables/',
  path: '/tables/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesTableIdRoute = TablesTableIdRouteImport.update({
  id: '/tables/$tableId',
  path: '/tables/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables/': typeof TablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables': typeof TablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/tables/$tableId': typeof TablesTableIdRoute
  '/tables/': typeof TablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/health' | '/tables/$tableId' | '/tables/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/health' | '/tables/$tableId' | '/tables'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/health'
    | '/tables/$tableId'
    | '/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  TablesTableIdRoute: typeof TablesTableIdRoute
  TablesIndexRoute: typeof TablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/': {
      id: '/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof TablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables/$tableId': {
      id: '/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/tables/$tableId'
      preLoaderRoute: typeof TablesTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  TablesTableIdRoute: TablesTableIdRoute,
  TablesIndexRoute: TablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
